function EEG_uni = unipolar(EEG_bipolar)
% This funcion converts the data from bipolar to unipolar.
% Input
%       EEG_bipolar = EEG bipolar data set
% Output
%       EEG_uni = EEG unipolar data set

% The data set, EEG_bipolar, is on the form 
%           Xb = MX 
% Where 
%       Xb: the bipolar data set, EEG_bipolar 
%       X:  the orignal unipolar data, EEG_uni. 
%       M: he bipolar-referencing transform matrix

% To convert the data we need to solve for X so 
%           X = M^-1*Xb

% Start by constructing M. How to construct M can be seen from the
% EEG_bipolar.chanloc.labels 
M = zeros(23,21);
% Make a 23 x 2 matrix that has the column index for 1 and -1
column_index = [1 2; ...
                2 3; ...
                3 4; ...
                4 5; ...
                1 6; ...
                6 7; ...
                7 8; ...
                8 5; ...
                9 10; ...
                10 11; ...
                11 12; ...
                12 13; ...
                9 14; ...
                14 15; ...
                15 16; ...
                16 13; ...
                17 18; ...
                18 19; ...
                4 3; ...
                3 20; ...
                20 21; ...
                21 15; ...
                15 16];
for row_index = 1:23
    M(row_index,column_index(row_index,1)) = 1;
    M(row_index,column_index(row_index,2)) = -1;
end 
                
% Now we can recunstruct the data from bipolar to unipolar 
% To convert the data we need to solve for X so 
%           X = M^-1*Xb
EEG_uni = EEG_bipolar;
EEG_uni.data = pinv(M)*EEG_bipolar.data;
EEG_uni.nbchan = 21; % change the number of channels 

% Now we need to change the channel labels so it matches with our
% reconstructed data 
EEG_uni.chanlocs(22:23) = [] % Making the chanlocks the right size
uni_chanlocs = {'FP1', 'F7', 'T7', 'P7', 'O1', 'F3', 'C3', 'P3', 'FP2', 'F4', 'C4', 'P4', 'O2', 'F8', 'T8', 'P8', 'FZ', 'CZ', 'PZ', 'FT9', 'FT10'};

for i = 1:21
    EEG_uni.chanlocs(i).labels = uni_chanlocs{i}
end 

end 